# Site settings
title: BH5HBI
email: 2225945@qq.com
description: > # this means to ignore newlines until "baseurl:"
  de BH5HBI.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bh5hbi.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
